# Generated by Django 3.1.4 on 2021-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=5000)),
                ('job_creator', models.CharField(max_length=120)),
                ('payment', models.IntegerField()),
                ('skills', models.ManyToManyField(to='main.Skill')),
            ],
        ),
    ]
