# Generated by Django 3.1.4 on 2021-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Machine Learning', 'Machine Learning')], default='Web Development', max_length=120),
        ),
    ]
