# Generated by Django 3.1.4 on 2021-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city_name',
            field=models.CharField(default='Pune', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='country_name',
            field=models.CharField(default='India', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(max_length=5000),
        ),
    ]
